#!/bin/sh
mkdir -p "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png"
mkdir -p "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/psd"
mkdir -p "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/txt"
cp -f "./Resources/raw/BothEndsArrowTool.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/BothEndsArrowTool.png"
cp -f "./Resources/raw/BothEndsArrowTool@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/BothEndsArrowTool@2x.png"
cp -f "./Resources/raw/BothEndsArrowTool@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/BothEndsArrowTool@3to2x.png"
cp -f "./Resources/raw/BothEndsArrowToolDark.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/BothEndsArrowToolDark.png"
cp -f "./Resources/raw/BothEndsArrowToolDark@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/BothEndsArrowToolDark@2x.png"
cp -f "./Resources/raw/BothEndsArrowToolDark@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/BothEndsArrowToolDark@3to2x.png"
cp -f "./Resources/raw/HeadArrowTool.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/HeadArrowTool.png"
cp -f "./Resources/raw/HeadArrowTool@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/HeadArrowTool@2x.png"
cp -f "./Resources/raw/HeadArrowTool@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/HeadArrowTool@3to2x.png"
cp -f "./Resources/raw/HeadArrowToolDark.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/HeadArrowToolDark.png"
cp -f "./Resources/raw/HeadArrowToolDark@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/HeadArrowToolDark@2x.png"
cp -f "./Resources/raw/HeadArrowToolDark@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/HeadArrowToolDark@3to2x.png"
cp -f "./Resources/raw/MultiArrowTool.psd" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/psd/MultiArrowTool.psd"
cp -f "./Resources/raw/StraightLineTool.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/StraightLineTool.png"
cp -f "./Resources/raw/StraightLineTool@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/StraightLineTool@2x.png"
cp -f "./Resources/raw/StraightLineTool@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/StraightLineTool@3to2x.png"
cp -f "./Resources/raw/StraightLineToolDark.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/StraightLineToolDark.png"
cp -f "./Resources/raw/StraightLineToolDark@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/StraightLineToolDark@2x.png"
cp -f "./Resources/raw/StraightLineToolDark@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/StraightLineToolDark@3to2x.png"
cp -f "./Resources/raw/TailArrowTool.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/TailArrowTool.png"
cp -f "./Resources/raw/TailArrowTool@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/TailArrowTool@2x.png"
cp -f "./Resources/raw/TailArrowTool@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/TailArrowTool@3to2x.png"
cp -f "./Resources/raw/TailArrowToolDark.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/TailArrowToolDark.png"
cp -f "./Resources/raw/TailArrowToolDark@2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/TailArrowToolDark@2x.png"
cp -f "./Resources/raw/TailArrowToolDark@3to2x.png" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/png/TailArrowToolDark@3to2x.png"
cp -f "./Resources/raw/IDToFile.txt" "${CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}.aip/Contents/Resources/txt/IDToFile.txt"

exit
